hashicorp/go-eventlogger

filters/encrypt/classification.go
filters/encrypt/filter_operation.go
filters/encrypt/filter_operation_test.go
filters/encrypt/options.go
filters/encrypt/options_test.go
filters/encrypt/tag.go
filters/encrypt/tag_test.go

This is the start of implementing the new node described in ENG-034
`jimlambrt-encrypt-filter-feature` will be a long-lived branch for all the PRs related to this on-going implementation.  Once all the PRs required to fully implement the feature have been reviewed and merged into this long-lived branch it will be merged into main and the new feature will be generally available. 
There is a work in progress (wip) branch that contains much of the completed feature and is the source for these on-going implementation PRs.  This wip branch (`jimlambrt-encrypt-feature-wip`) is subject to ongoing changes but it reviewers should feel free to reference it for more contextual information about any of these implementation PRs.
thanks, 
j.

Encrypt Filter: add classifications, filter operations and tag functions

---

sinks/writer/writer_test.go

Currently `gotestsum` was incorrectly stated that a few unit tests failed because they wrote to stdout without a newline.  This is sort of a "known" problem highlighted in this issue: https://github.com/golang/go/issues/38063
This PR simply adds a newline to the output to stop these false positives.

add newline to test output written to stdout for Writer sink.

---

file_sink.go
file_sink_test.go

When a non-default file sink mode is configured, the parent directory's permissions are also modified to match the configured mode. If the desired mode does not include execute permissions, the permission change effectively removes the ability for a non-root user to enter into the directory.
This change makes it so that only the created file's permissions are modified. The parent directory's permissions are unchanged if the directory already exists.

Don't set permissions on pre-existing parent dir

---

filters/encrypt/README.md
filters/encrypt/docs_test.go
filters/encrypt/filter.go
filters/encrypt/filter_test.go
filters/encrypt/filter_test_pkg_test.go
filters/encrypt/map.go
filters/encrypt/map_test.go
filters/encrypt/options.go
filters/encrypt/options_test.go
filters/encrypt/testing/resources/protopayload/taggable.go

Currently, map fields are only filtered if a `Taggable` interface is implemented which includes the map. This is efficient, but could result in an inadvertent leak of sensitive and/or secret data. This PR changes that behavior by tracking all maps which are encountered while processing the event and before returning, it filters all the remaining unfiltered maps fields.

Events: filter map fields which are not tagged.

---

.github/workflows/go.yml
file_sink.go
file_sink_test.go
filters/gated/gated_test.go

Backward compatible version of #62 -- This version does *not* change the
default behavior. Users must opt in to new behavior.
This patch updates the file sink to allow *not* appending the timestamp
on the current log file. In this mode the timestamp is only appended
when the file is rotated.
This matches the behavior:
- Implemented in Nomad v1.1.4 with hashicorp/nomad#11070
- Requested in hashicorp/nomad#11061
> The following example configures a destination called "My Sink" which
> stores audit events at the file `/tmp/audit.json`.
Nomad's documentation is a little vague but implies the prior behavior
of always appending a timestamp.

allow not appending timestamp to current log file

---

filters/encrypt/CHANGELOG.md
filters/encrypt/filter.go
filters/encrypt/filter_test_pkg_test.go
filters/encrypt/testing.go

When a slice contains values which implement the Taggable interface,
we will filter those items based on the values of its Taggable.Tags().
Prior to this fix, we were not checking to see if the items in
a slice had implemented the Taggable interface.

fix (encrypt): Support slice of taggable values

---

formatter_filters/cloudevents/formatter_filter.go
formatter_filters/cloudevents/formatter_filter_test.go
go.mod
go.sum

Added FormatterFilter.SignEventTypes which defines the types of
events that will be "signed".  If the event type isn't in this
list, then it won't be "signed".

fix (cloudevents): Add support to limit which event types are signed

---

broker.go
broker_test.go
go.mod
graph.go
graph_test.go
graphmap.go

I ran into a race condition related to the `graph.roots` map, e.g.,
https://app.circleci.com/pipelines/github/hashicorp/vault/50560/workflows/96d003c2-185e-4504-a4c0-fab481ed6282/jobs/594936
happens when registering and removing a pipeline (which accesses a `graph`'s `roots` map) when another goroutine is iterating through the map in, for example, `graph.process()`. The pipeline registering and removing are protected by the broker's lock, but the `graph.process()` is *not* protected by the lock (since it does not have access to it).
Adding another lock for `graph.roots` might be messy and lead to deadlock possibilities, so I thought the easiest way to resolve this was to switch to a `sync.Map`.
I confirmed that this change fixes the above race condition in Vault's tests.

Use sync.Map for graph roots map

---

.gitignore
node.go
node_test.go

`linkNodes` doesn't link the `node` to the `nodeID`, which does happen for sinks under `linkNodesAndSinks`, this change makes them behave in the same way.

Updated linkNodes to include the nodeID

---

broker.go
graph.go
graph_test.go

Note: we need to rebase this once [#86](https://github.com/hashicorp/go-eventlogger/pull/86) has been merged.

tests: explicitly test success thresholds with filtered events

---

broker.go
broker_test.go
filters/gated/docs_test.go
filters/gated/gated_test.go
formatter_filters/cloudevents/docs_test.go
graphmap.go
graphmap_test.go
node.go
node_test.go
sinks/writer/docs_test.go

This PR adds the ability to remove nodes which are referenced to form part of a pipeline, given that the nodes are **not** in use by any other pipelines.
Whilst this behaviour may not be required for most use-cases, we've encountered ways in which a consumer of the library (Vault) would need to be able to clear up after itself to prevent memory leaks and performance issues.

Unregister nodes along with pipeline

---

filters/gated/gated.go
filters/gated/gated_test.go

Supporting the Closer interface means that a gated filter will properly flush all its events when asked to Close(...)

feat (filters/gated): add support for Closer interface

---

broker.go

`RemovePipelineAndNodes` go doc comment indicated that once we begin removing the pipeline and associated nodes, we will return `false` along with any error, but we only do that if we fail pre-conditions. 
Instead the comment should be updated to reflect the actual logic, which is to return `true` (that at least the pipeline was removed but node removal may have caused error).

Fix: go doc comments for RemovePipelineAndNodes

---

file_sink.go

This looks to be a hangover from Vault related logic, `discard` is not used anywhere else in the `FileSink`.

remove 'discard' from file sink

---

sinks/channel/channel_sink.go
sinks/channel/channel_sink_test.go
sinks/channel/docs.go
sinks/channel/docs_test.go

Adds a channel sink to allow sending events to a channel

feat(channel sink): add channel sink type

---

broker.go
broker_test.go
error.go

Addition of a DeregisterNode function, which will remove a node from the broker, if it is not currently  in use
This is useful if RegisterNode was used successfully prior to a failed RegisterPipeline call referencing those nodes

broker: add DeregisterNode function

---

broker.go

Small go doc update to make it clearer to the consumer that only nodes which have effectively 'terminated' the pipeline successfully will appear in the return value of `Complete()` and `CompleteSinks()` (and their underlying fields `complete` and `completeSinks`.

Broker `Status`: Updated go docs for `Complete()` and `CompleteSinks()`

---

broker.go
broker_test.go
file_sink_test.go

This PR adds two methods which return the value of the thresholds set on the broker for a given event type (along with a value indicating whether they were set at all).
Some tests have been added, and other tests parallelized to make things a bit quicker.

Provide 'getter' receivers for `Broker`s `successThreshold` and `successThresholdSinks`

---

sinks/writer/writer.go
sinks/writer/writer_test.go

The included test will show data races in the race detector if the safety goes away.

Add lock to writer sink to ensure thread safety

---

.github/workflows/go.yml
broker.go
broker_test.go
go.mod
graph.go

Improvement: 
When the `Broker` performs a `Send` and decides what the returned error should look like, we can include the state of the context (`context.Err()`) at that moment and allow `getError` to decide if context information needs to be included in the return.
This allows callers to understand why the `Broker` may have ended processing early.
Change:
This PR also updates the required version of Go from `1.16` to `1.20` as we now use [`errors.Join`](https://pkg.go.dev/errors#Join) added in `1.20`. Updates are made to the `go.mod` and CI files and a `go mod tidy` performed.
It also updates the GHA for checkout and go-version.

broker: `Send` return error can be context aware.

---

.github/dependabot.yaml

As per the memo: https://go.hashi.co/memo/eng-004,
Enabling the dependabot for identifying and updating the security and version updates in the repositories rather handling it manually.

Addition of dependabot.yaml
